<?php
// $Id$
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

function style_edit_menu() {
    $items['admin/settings/styleedit'] = array(

            'title' => 'Style Editor',
            'description' => 'Edit theme stylesheets',
            'page callback' => 'style_edit_list_filesystem',
            'access arguments' => array('view style sheets'),
            'type' => MENU_NORMAL_ITEM,
            //'file' => 'annotate.admin.inc',
            );
    
    $items['admin/settings/styleedit/listfs'] = array(

            'title' => 'List from Filesystem',
            'page callback' => 'style_edit_list_filesystem',
            'access arguments' => array('view style sheets'),
            'type' => MENU_LOCAL_TASK,
            );


    $items['admin/settings/styleedit/listdb'] = array(

            'title' => 'List from database',
            'page callback' => 'style_edit_list_database',
            'access arguments' => array('view style sheets'),
            'type' => MENU_LOCAL_TASK,
            );


    $items['admin/settings/styleedit/%/view'] = array(

            'title' => 'View',
            'page callback' => 'style_edit_theme_view',
            'page arguments' => array(3),
            'access arguments' => array('view style sheets'),
            );

    $items['admin/settings/styleedit/import/%/%/%'] = array(

            'title' => 'Import',
            'page callback' => 'style_edit_theme_import',
            'page arguments' => array(4,5,6),
            'access arguments' => array('import style sheets'),
            );

    $items['admin/settings/styleedit/edit/%'] = array(

            'title' => 'Edit',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('style_edit_styleset_edit_form',4),
            'access arguments' => array('edit style sheets'),
            'file' => 'style_edit_form.inc',
            );

    return $items;
}

function style_edit_perm() {
    return array(
        'view style sheets',
        'import style sheets',
        'update style sheets',
        'edit style sheets',
        );
}

function style_edit_settings(){

    $form['list'] = array(
        '#type' => 'textarea',
        '#title' => 'List',
    );
return $form;
}


function style_edit_list_filesystem(){
    //dargs();
    dpm(list_themes());
    dpm(query_style_array('all'));

    return build_table(query_style_array('all'));
}

function style_edit_theme_view($theme){
    //dargs();
    return build_table(query_style_array($theme));
}


function query_style_array($theme){
    // TODO: use list_theme()
    $type = 'theme';
    if ($theme == 'all'){
        $sql = "SELECT info, name FROM {system} WHERE type = '%s'";
    }
    else {
        $sql = "SELECT info, name FROM {system} WHERE type = '%s' AND name = '%s'";
    }

    $result = db_query($sql,$type,$theme);

    $rows[] = array();

    while ($r = db_fetch_array($result)) {
        $rows[] = $r;
    }
    return $rows;
}

function build_table($rows){
    $header = array(
        array('data' => t('Theme'), 'field' => 'name'),
        array('data' => t('Type'), 'field' => 'style'),
        array('data' => t('Operation'), 'field' => 'op'),
        );

    $table[] = array();
    $info = array();

    foreach ($rows as $value){
        $info = unserialize($value['info']);
        if (count($value)==0) continue;
        foreach ($info['stylesheets'] as $st_key => $st_value){
            foreach ($st_value as $key => $style){
            $table[] = array(
                l($info['name'],'admin/settings/styleedit/' . $value['name'] . '/view'),
                $st_key . ' => ' . $style,
                l(t('import'),'admin/settings/styleedit/import/' . $value['name'] . '/'. $st_key .'/' . $key),
            );
            }
        }
    }

    return theme('table',$header,$table);
}

function style_edit_theme_import($theme,$stylesesction,$stylesheet){
    drupal_add_tabledrag('stylesheet_table', 'order', 'sibling', 'weight-group');
    $header = array(
        array('data' => t('ID'), 'field' => 'id'),
        array('data' => t('Class / Element'), 'field' => 'selector'),
        array('data' => t('CSS'), 'field' => 'style'),
        array('data' => t('Operation'), 'field' => 'op'),
        );


    $rows = query_style_array($theme);
    $info = unserialize($rows[1][info]);
    $cssfilename = $info['stylesheets'][$stylesesction][$stylesheet];
    $styles = get_style_sections_from_file($cssfilename);
    dpm($styles);
    dpm($info);

    $filedata = array(
        'name' => $info['name'],
        'systemname' => $theme,
        'filename' => $stylesheet,
        'path' => $cssfilename,
        'ufiletimestamp' => 1,
    );

    $sql = 'SELECT cssid,ufiletimestamp FROM {style_edit_cssimport} WHERE name = %s AND path = %s';
    $result = db_query($sql);

    drupal_write_record('style_edit_cssimport', $filedata);

    $id = 1;
    $sortval = 100;
    foreach ($styles[0] as $key => $style) {
        if ($styles[2][$key] == '') continue;
        $line = split('{', $style);
        $stylecontend = str_replace(';', ';<br>',str_replace('}','', $line[1]));
        $table[] = array(
            $id,
            $line[0],
            $stylecontend,
            l(t(edit), 'admin/settings/styleedit/edit/'.$id),
        );
        $id++;
        $sortval++;

    }
    drupal_set_message(t('Import OK'));
    return theme('table',$header,$table,array('id'=>'stylesheet_table'));
    //return $theme . ' ' . $style . ' ' . $info['stylesheets'][$stylesesction][$stylesheet];
}

function get_style_sections_from_file($file){
    $arrChunks = array();

    $str_style = file_get_contents($file);
    $str_style = str_replace("\r", '', $str_style);
    $str_style = str_replace('/**/', '[__]', $str_style);
    if (substr($str_style, 0, 2) != '/*'){
	$str_style = "\n" . $str_style;
    }
    preg_match_all('@(/\*.*\*\/)|([^\/}]*{[^}]*})@Us', $str_style, $arrChunks);
    return $arrChunks;
}

function style_edit_list_database() {
    // TODO: implement database listing
    require_once 'style_edit_db_tables.inc';
    dpm(style_edit_schema_definition());
    return 'not done yet';
}

?>
