<?php
// $Id$
/**
 * @file
 * Install, update and uninstall functions for the style_edit module.
 */

function style_edit_schema() {
    require_once 'style_edit_db_tables.inc';
    return style_edit_schema_definition();
}

function style_edit_install() {
    drupal_install_schema('style_edit');
    variable_set('style_edit_editor_type', 'text');
}

function style_edit_uninstall() {
    drupal_uninstall_schema('style_edit');
    variable_del('style_edit_editor_type');
}

?>