<?php
// $Id$
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
*/

function style_edit_menu() {
    $items['admin/styleedit'] = array(

            'title' => 'Style Editor',
            'description' => 'Edit Style Sheets',
            'page callback' => 'style_edit_overview',
            'page arguments' => array('style_edit_settings'),
            'access arguments' => array('view style sheets'),
            'type' => MENU_NORMAL_ITEM,
            //'file' => 'annotate.admin.inc',
            );
    
    $items['admin/styleedit/%/view'] = array(

            'title' => 'Edit',
            'page callback' => 'style_edit_theme_view',
            'page arguments' => array(2),
            'access arguments' => array('view style sheets'),
            'type' => MENU_LOCAL_TASK,
            );

    $items['admin/styleedit/%/view/%/%/edit'] = array(

            'title' => 'Edit',
            'page callback' => 'style_edit_theme_edit',
            'page arguments' => array(2,4,5),
            'access arguments' => array('edit style sheets'),
            'type' => MENU_LOCAL_TASK,
            );

    return $items;
}

function style_edit_perm() {
    return array('view style sheets',
        'edit style sheets',
        );
}

function style_edit_settings(){

    $form['list'] = array(
        '#type' => 'textarea',
        '#title' => 'List',
    );
return $form;
}


function style_edit_overview(){
    return build_table(query_style_array('all'));
}

function style_edit_theme_view($theme){
    return build_table(query_style_array($theme));
}


function query_style_array($theme){
    $type = 'theme';
    if ($theme == 'all'){
        $sql = "SELECT info, name FROM {system} WHERE type = '%s'";
    }
    else {
        $sql = "SELECT info, name FROM {system} WHERE type = '%s' AND name = '%s'";
    }

    $result = db_query($sql,$type,$theme);

    $rows[] = array();

    while ($r = db_fetch_array($result)) {
        $rows[] = $r;
    }

    return $rows;
}

function build_table($rows){
    $header = array(
        array('data' => t('Theme'), 'field' => 'name'),
        array('data' => t('Type'), 'field' => 'style'),
        array('data' => t('Operation'), 'field' => 'op'),
        );

    $table[] = array();
    $info = array();

    foreach ($rows as $value){
        $info = unserialize($value['info']);
        if (count($value)==0) continue;
        foreach ($info['stylesheets'] as $st_key => $st_value){
            foreach ($st_value as $key => $style){
            $table[] = array(
                l($info['name'],'admin/styleedit/' . $value['name'] . '/view'),
                $st_key . ' => ' . $style,
                l(t('edit'),'admin/styleedit/' . $value['name'] . '/view/'. $st_key .'/' . $key .'/edit'),
            );
            }
        }
    }

    return theme('table',$header,$table);
}

function style_edit_theme_edit($theme,$stylesesction,$style){
    $rows = query_style_array($theme);
    $info = unserialize($rows[1][info]);
    //print_r(file($info['stylesheets'][$stylesesction][$style]));
    return $theme . ' ' . $style . ' ' . $info['stylesheets'][$stylesesction][$style];
}
?>
